//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SalesShop
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Магазин.
    /// </summary>
    //  *** Start programmer edit section *** (Магазин CustomAttributes)

    //  *** End programmer edit section *** (Магазин CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МагазинE", new string[] {
            "Название as \'Название\'",
            "Адрес as \'Адрес\'"})]
    [View("МагазинL", new string[] {
            "Название as \'Название\'",
            "Адрес as \'Адрес\'"})]
    public class Магазин : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private string fАдрес;
        
        //  *** Start programmer edit section *** (Магазин CustomMembers)

        //  *** End programmer edit section *** (Магазин CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        //  *** Start programmer edit section *** (Магазин.Название CustomAttributes)

        //  *** End programmer edit section *** (Магазин.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                //  *** Start programmer edit section *** (Магазин.Название Get start)

                //  *** End programmer edit section *** (Магазин.Название Get start)
                string result = this.fНазвание;
                //  *** Start programmer edit section *** (Магазин.Название Get end)

                //  *** End programmer edit section *** (Магазин.Название Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Магазин.Название Set start)

                //  *** End programmer edit section *** (Магазин.Название Set start)
                this.fНазвание = value;
                //  *** Start programmer edit section *** (Магазин.Название Set end)

                //  *** End programmer edit section *** (Магазин.Название Set end)
            }
        }
        
        /// <summary>
        /// Адрес.
        /// </summary>
        //  *** Start programmer edit section *** (Магазин.Адрес CustomAttributes)

        //  *** End programmer edit section *** (Магазин.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                //  *** Start programmer edit section *** (Магазин.Адрес Get start)

                //  *** End programmer edit section *** (Магазин.Адрес Get start)
                string result = this.fАдрес;
                //  *** Start programmer edit section *** (Магазин.Адрес Get end)

                //  *** End programmer edit section *** (Магазин.Адрес Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Магазин.Адрес Set start)

                //  *** End programmer edit section *** (Магазин.Адрес Set start)
                this.fАдрес = value;
                //  *** Start programmer edit section *** (Магазин.Адрес Set end)

                //  *** End programmer edit section *** (Магазин.Адрес Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МагазинE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МагазинE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МагазинE", typeof(IIS.SalesShop.Магазин));
                }
            }
            
            /// <summary>
            /// "МагазинL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МагазинL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МагазинL", typeof(IIS.SalesShop.Магазин));
                }
            }
        }
    }
}
