//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SalesShop
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Продажа.
    /// </summary>
    //  *** Start programmer edit section *** (Продажа CustomAttributes)

    //  *** End programmer edit section *** (Продажа CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПродажаE", new string[] {
            "Дата as \'Дата\'",
            "Магазин as \'Магазин\'",
            "Магазин.Название as \'Название\'"})]
    [AssociatedDetailViewAttribute("ПродажаE", "СтрокаПродажи", "СтрокаПродажиE", true, "", "Строка продажи", true, new string[] {
            ""})]
    [View("ПродажаL", new string[] {
            "Дата as \'Дата\'",
            "Магазин.Название as \'Название\'"})]
    public class Продажа : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.SalesShop.Магазин fМагазин;
        
        private IIS.SalesShop.DetailArrayOfСтрокаПродажи fСтрокаПродажи;
        
        //  *** Start programmer edit section *** (Продажа CustomMembers)

        //  *** End programmer edit section *** (Продажа CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        //  *** Start programmer edit section *** (Продажа.Дата CustomAttributes)

        //  *** End programmer edit section *** (Продажа.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                //  *** Start programmer edit section *** (Продажа.Дата Get start)

                //  *** End programmer edit section *** (Продажа.Дата Get start)
                System.DateTime result = this.fДата;
                //  *** Start programmer edit section *** (Продажа.Дата Get end)

                //  *** End programmer edit section *** (Продажа.Дата Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Продажа.Дата Set start)

                //  *** End programmer edit section *** (Продажа.Дата Set start)
                this.fДата = value;
                //  *** Start programmer edit section *** (Продажа.Дата Set end)

                //  *** End programmer edit section *** (Продажа.Дата Set end)
            }
        }
        
        /// <summary>
        /// Продажа.
        /// </summary>
        //  *** Start programmer edit section *** (Продажа.Магазин CustomAttributes)

        //  *** End programmer edit section *** (Продажа.Магазин CustomAttributes)
        [NotNull()]
        public virtual IIS.SalesShop.Магазин Магазин
        {
            get
            {
                //  *** Start programmer edit section *** (Продажа.Магазин Get start)

                //  *** End programmer edit section *** (Продажа.Магазин Get start)
                IIS.SalesShop.Магазин result = this.fМагазин;
                //  *** Start programmer edit section *** (Продажа.Магазин Get end)

                //  *** End programmer edit section *** (Продажа.Магазин Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Продажа.Магазин Set start)

                //  *** End programmer edit section *** (Продажа.Магазин Set start)
                this.fМагазин = value;
                //  *** Start programmer edit section *** (Продажа.Магазин Set end)

                //  *** End programmer edit section *** (Продажа.Магазин Set end)
            }
        }
        
        /// <summary>
        /// Продажа.
        /// </summary>
        //  *** Start programmer edit section *** (Продажа.СтрокаПродажи CustomAttributes)

        //  *** End programmer edit section *** (Продажа.СтрокаПродажи CustomAttributes)
        public virtual IIS.SalesShop.DetailArrayOfСтрокаПродажи СтрокаПродажи
        {
            get
            {
                //  *** Start programmer edit section *** (Продажа.СтрокаПродажи Get start)

                //  *** End programmer edit section *** (Продажа.СтрокаПродажи Get start)
                if ((this.fСтрокаПродажи == null))
                {
                    this.fСтрокаПродажи = new IIS.SalesShop.DetailArrayOfСтрокаПродажи(this);
                }
                IIS.SalesShop.DetailArrayOfСтрокаПродажи result = this.fСтрокаПродажи;
                //  *** Start programmer edit section *** (Продажа.СтрокаПродажи Get end)

                //  *** End programmer edit section *** (Продажа.СтрокаПродажи Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Продажа.СтрокаПродажи Set start)

                //  *** End programmer edit section *** (Продажа.СтрокаПродажи Set start)
                this.fСтрокаПродажи = value;
                //  *** Start programmer edit section *** (Продажа.СтрокаПродажи Set end)

                //  *** End programmer edit section *** (Продажа.СтрокаПродажи Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПродажаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродажаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродажаE", typeof(IIS.SalesShop.Продажа));
                }
            }
            
            /// <summary>
            /// "ПродажаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПродажаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПродажаL", typeof(IIS.SalesShop.Продажа));
                }
            }
        }
    }
}
